"""init

Revision ID: ee3b7fdf4cfa
Revises: 
Create Date: 2026-01-29 16:30:47.404345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import PostgreSQL specific dialects for JSONB and UUID support
from sqlalchemy.dialects import postgresql 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee3b7fdf4cfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_metadata',
    sa.Column('workflow_defn_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_defn', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('workflow_defn_id')
    )
    op.create_index(op.f('ix_workflow_metadata_name'), 'workflow_metadata', ['name'], unique=False)
    op.create_table('workflow_execution',
    sa.Column('workflow_execution_id', sa.String(), nullable=False),
    sa.Column('workflow_defn_id', sa.String(), nullable=False),
    sa.Column('workflow_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='workflowstatus'), nullable=False),
    sa.Column('workflow_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['workflow_defn_id'], ['workflow_metadata.workflow_defn_id'], ),
    sa.PrimaryKeyConstraint('workflow_execution_id')
    )
    op.create_table('workflow_task_execution',
    sa.Column('workflow_execution_id', sa.String(), nullable=False),
    sa.Column('workflow_task_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('workflow_defn_id', sa.String(), nullable=False),
    sa.Column('workflow_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='workflowstatus'), nullable=False),
    sa.Column('workflow_task_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_task_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['workflow_defn_id'], ['workflow_metadata.workflow_defn_id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_execution.workflow_execution_id'], ),
    sa.PrimaryKeyConstraint('workflow_execution_id', 'workflow_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_task_execution')
    op.drop_table('workflow_execution')
    op.drop_index(op.f('ix_workflow_metadata_name'), table_name='workflow_metadata')
    op.drop_table('workflow_metadata')
    # ### end Alembic commands ###